<?php

declare(strict_types=1);

namespace Lodgik\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Lodgik\Entity\Contract\TenantAware;
use Lodgik\Entity\Traits\HasUuid;
use Lodgik\Entity\Traits\HasTenant;
use Lodgik\Entity\Traits\HasTimestamps;

/**
 * Single-use digital voucher for amenity access (gym, pool, spa, etc.).
 * Generated by hotel, redeemed by guest at amenity point.
 */
#[ORM\Entity]
#[ORM\Table(name: 'amenity_vouchers')]
#[ORM\Index(columns: ['tenant_id', 'booking_id'], name: 'idx_av_booking')]
#[ORM\Index(columns: ['tenant_id', 'code'], name: 'idx_av_code')]
#[ORM\HasLifecycleCallbacks]
class AmenityVoucher implements TenantAware
{
    use HasUuid;
    use HasTenant;
    use HasTimestamps;

    #[ORM\Column(name: 'booking_id', type: Types::STRING, length: 36)]
    private string $bookingId;

    #[ORM\Column(name: 'property_id', type: Types::STRING, length: 36)]
    private string $propertyId;

    #[ORM\Column(name: 'guest_id', type: Types::STRING, length: 36)]
    private string $guestId;

    /** 'gym' | 'pool' | 'spa' | 'sauna' | 'lounge' | 'other' */
    #[ORM\Column(name: 'amenity_type', type: Types::STRING, length: 20)]
    private string $amenityType;

    #[ORM\Column(name: 'amenity_name', type: Types::STRING, length: 100)]
    private string $amenityName;

    /** 10-char voucher code */
    #[ORM\Column(type: Types::STRING, length: 10)]
    private string $code;

    #[ORM\Column(name: 'valid_date', type: Types::DATE_IMMUTABLE)]
    private \DateTimeImmutable $validDate;

    #[ORM\Column(name: 'max_uses', type: Types::INTEGER, options: ['default' => 1])]
    private int $maxUses = 1;

    #[ORM\Column(name: 'use_count', type: Types::INTEGER, options: ['default' => 0])]
    private int $useCount = 0;

    /** 'active' | 'used' | 'expired' | 'revoked' */
    #[ORM\Column(type: Types::STRING, length: 10, options: ['default' => 'active'])]
    private string $status = 'active';

    #[ORM\Column(name: 'redeemed_at', type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $redeemedAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    public function __construct(string $bookingId, string $propertyId, string $guestId, string $amenityType, string $amenityName, \DateTimeImmutable $validDate, string $tenantId)
    {
        $this->generateId();
        $this->bookingId = $bookingId;
        $this->propertyId = $propertyId;
        $this->guestId = $guestId;
        $this->amenityType = $amenityType;
        $this->amenityName = $amenityName;
        $this->validDate = $validDate;
        $this->code = 'V' . strtoupper(substr(bin2hex(random_bytes(5)), 0, 9));
        $this->setTenantId($tenantId);
    }

    public function getBookingId(): string { return $this->bookingId; }
    public function getPropertyId(): string { return $this->propertyId; }
    public function getGuestId(): string { return $this->guestId; }
    public function getAmenityType(): string { return $this->amenityType; }
    public function getAmenityName(): string { return $this->amenityName; }
    public function getCode(): string { return $this->code; }
    public function getValidDate(): \DateTimeImmutable { return $this->validDate; }
    public function getMaxUses(): int { return $this->maxUses; }
    public function setMaxUses(int $v): void { $this->maxUses = $v; }
    public function getUseCount(): int { return $this->useCount; }
    public function getStatus(): string { return $this->status; }
    public function getRedeemedAt(): ?\DateTimeImmutable { return $this->redeemedAt; }
    public function getNotes(): ?string { return $this->notes; }
    public function setNotes(?string $v): void { $this->notes = $v; }

    public function canRedeem(): bool
    {
        return $this->status === 'active' && $this->useCount < $this->maxUses && $this->validDate >= new \DateTimeImmutable('today');
    }

    public function redeem(): void
    {
        $this->useCount++;
        $this->redeemedAt = new \DateTimeImmutable();
        if ($this->useCount >= $this->maxUses) $this->status = 'used';
    }

    public function revoke(): void { $this->status = 'revoked'; }

    public function toArray(): array
    {
        return [
            'id' => $this->getId(), 'booking_id' => $this->bookingId, 'guest_id' => $this->guestId,
            'amenity_type' => $this->amenityType, 'amenity_name' => $this->amenityName,
            'code' => $this->code, 'valid_date' => $this->validDate->format('Y-m-d'),
            'max_uses' => $this->maxUses, 'use_count' => $this->useCount, 'status' => $this->status,
            'redeemed_at' => $this->redeemedAt?->format('Y-m-d H:i:s'),
            'notes' => $this->notes, 'created_at' => $this->getCreatedAt()?->format('Y-m-d H:i:s'),
        ];
    }
}
