import {
  LucideAngularModule,

  // ─── Daily Operation ──────────────────
  LayoutDashboard,
  ClipboardList,
  Hotel,
  Tag,
  UserRound,
  SprayCan,
  SlidersHorizontal,

  // ─── Guest Experience ─────────────────
  ConciergeBell,
  MessageCircle,
  Gift,
  Heart,
  Shield,

  // ─── F&B & Facilities ─────────────────
  Utensils,
  BookOpen,
  Sparkles,
  Dumbbell,
  Bath,

  // ─── Finance & Reports ────────────────
  FolderOpen,
  FileText,
  Receipt,
  Moon,
  TrendingUp,
  Users,
  ChartBar,
  FileChartColumn,
  ShieldAlert,
  ShieldCheck,
  Banknote,
  CalendarCheck,

  // ─── Human Resources ──────────────────
  UserRoundCog,
  Clock,
  TreePalm,
  HandCoins,
  Star,
  Briefcase,

  // ─── Maintenance & Assets ─────────────
  Package,
  TriangleAlert,
  Wrench,
  HardHat,

  // ─── Integrations ─────────────────────
  Globe,
  Smartphone,
  Wifi,
  Handshake,

  // ─── Guest Cards ──────────────────────
  ScanLine,
  Activity,
  Radio,

  // ─── System ───────────────────────────
  Building,
  Puzzle,
  Zap,
  CreditCard,
  Settings,
  Bell,
  LogOut,

  // ─── Navigation / UI ──────────────────
  ChevronLeft,
  ChevronDown,
  ChevronRight,
  Plus,
  Search,
  Home,
  BedDouble,
  DoorOpen,
  CalendarDays,
  ArrowDownRight,
  ArrowUpRight,
  CircleCheck,
  CircleX,
  UserCheck,
  Key,

  // ─── Inventory & Food Cost (added Phase D/E) ──────────────
  ArrowLeftRight,
  BarChart,
  BarChart2,
  Building2,
  ChefHat,
  Layers,
  ChartLine,
  MapPin,
  Percent,
  Settings2,
  TrendingDown,
  Truck,
} from 'lucide-angular';

/**
 * All icons used across the Lodgik apps.
 */
export const LODGIK_ICONS = {
  LayoutDashboard,
  ClipboardList,
  Hotel,
  Tag,
  UserRound,
  SprayCan,
  SlidersHorizontal,
  ConciergeBell,
  MessageCircle,
  Gift,
  Heart,
  Shield,
  Utensils,
  BookOpen,
  Sparkles,
  Dumbbell,
  Bath,
  FolderOpen,
  FileText,
  Receipt,
  Moon,
  TrendingUp,
  Users,
  ChartBar,
  FileChartColumn,
  ShieldAlert,
  ShieldCheck,
  Banknote,
  CalendarCheck,
  UserRoundCog,
  Clock,
  TreePalm,
  HandCoins,
  Star,
  Briefcase,
  Package,
  TriangleAlert,
  Wrench,
  HardHat,
  Globe,
  Smartphone,
  Wifi,
  Handshake,
  Building,
  Puzzle,
  Zap,
  CreditCard,
  Settings,
  Bell,
  LogOut,
  ScanLine,
  Activity,
  Radio,
  ChevronLeft,
  ChevronDown,
  ChevronRight,
  Plus,
  Search,
  Home,
  BedDouble,
  DoorOpen,
  CalendarDays,
  ArrowDownRight,
  ArrowUpRight,
  CircleCheck,
  CircleX,
  UserCheck,
  Key,

  // ─── Inventory & Food Cost ───────────────────────────────
  ArrowLeftRight,
  BarChart,
  BarChart2,
  Building2,
  ChefHat,
  Layers,
  ChartLine,
  MapPin,
  Percent,
  Settings2,
  TrendingDown,
  Truck,
};

/**
 * Pre-configured LucideAngularModule with all Lodgik icons.
 * Use in standalone component imports: `LucideModule`
 */
export const LucideModule = LucideAngularModule.pick(LODGIK_ICONS);
