import { Component, inject, OnInit, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';

type PageState = 'idle' | 'uploading' | 'done' | 'error' | 'expired' | 'used';

/**
 * Mobile Upload Page — /mobile-upload/:token
 *
 * Public, unauthenticated page shown on a staff member's phone after scanning
 * the QR code generated by QrFileUploadComponent.
 *
 * This page:
 *  1. Reads the token from the route
 *  2. Shows a large, thumb-friendly file picker
 *  3. POSTs the selected file to POST /api/upload/qr/{token}
 *  4. Shows a success confirmation (the desktop page polls and auto-updates)
 *
 * Design goals:
 *  - No login required
 *  - Optimised for single-handed mobile use (large tap targets)
 *  - Accepts images from camera or gallery, plus PDFs
 *  - Works in all major mobile browsers (iOS Safari, Android Chrome)
 */
@Component({
  selector: 'app-mobile-upload',
  standalone: true,
  template: `
    <div class="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6">

      <!-- Header -->
      <div class="text-center mb-8">
        <div class="text-4xl mb-3">📱</div>
        <h1 class="text-xl font-bold text-gray-800">Lodgik Upload</h1>
        <p class="text-sm text-gray-500 mt-1">Secure one-time file upload</p>
      </div>

      <!-- Expired -->
      @if (state() === 'expired') {
        <div class="bg-white rounded-2xl shadow-sm p-8 w-full max-w-sm text-center">
          <div class="text-4xl mb-3">⏰</div>
          <h2 class="text-lg font-semibold text-gray-800 mb-2">Link Expired</h2>
          <p class="text-sm text-gray-500">This upload link has expired. Ask the staff member to generate a new QR code.</p>
        </div>
      }

      <!-- Already used -->
      @if (state() === 'used') {
        <div class="bg-white rounded-2xl shadow-sm p-8 w-full max-w-sm text-center">
          <div class="text-4xl mb-3">✅</div>
          <h2 class="text-lg font-semibold text-gray-800 mb-2">Already Uploaded</h2>
          <p class="text-sm text-gray-500">This link has already been used. Ask staff to generate a new QR code if needed.</p>
        </div>
      }

      <!-- Idle — file picker -->
      @if (state() === 'idle') {
        <div class="bg-white rounded-2xl shadow-sm p-6 w-full max-w-sm">
          <h2 class="text-base font-semibold text-gray-800 mb-1">Upload File</h2>
          @if (label()) {
            <p class="text-sm text-gray-500 mb-4">{{ label() }}</p>
          } @else {
            <p class="text-sm text-gray-500 mb-4">Select a photo from your gallery or take a new one.</p>
          }

          <!-- Camera capture button -->
          <label class="block w-full py-4 px-6 bg-sage-600 text-white text-base font-semibold text-center rounded-xl cursor-pointer active:bg-sage-700 transition-colors mb-3">
            📷 Take Photo
            <input type="file" accept="image/*" capture="environment" class="hidden" (change)="onFileSelected($event)">
          </label>

          <!-- Gallery / file picker -->
          <label class="block w-full py-4 px-6 bg-white border-2 border-gray-200 text-gray-700 text-base font-semibold text-center rounded-xl cursor-pointer active:bg-gray-50 transition-colors">
            🖼️ Choose from Gallery / Files
            <input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" class="hidden" (change)="onFileSelected($event)">
          </label>

          @if (fileError()) {
            <p class="text-sm text-red-600 mt-3 text-center">{{ fileError() }}</p>
          }

          <p class="text-xs text-gray-400 text-center mt-4">Max 10 MB · JPEG, PNG, PDF</p>
        </div>
      }

      <!-- Uploading -->
      @if (state() === 'uploading') {
        <div class="bg-white rounded-2xl shadow-sm p-8 w-full max-w-sm text-center">
          <div class="w-12 h-12 border-4 border-sage-400 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <h2 class="text-base font-semibold text-gray-700">Uploading…</h2>
          <p class="text-sm text-gray-400 mt-1">Please wait, do not close this page.</p>
          @if (progress() > 0) {
            <div class="mt-4 h-2 bg-gray-100 rounded-full overflow-hidden">
              <div class="h-full bg-sage-500 rounded-full transition-all"
                   [style.width.%]="progress()"></div>
            </div>
            <p class="text-xs text-gray-400 mt-1">{{ progress() }}%</p>
          }
        </div>
      }

      <!-- Done -->
      @if (state() === 'done') {
        <div class="bg-white rounded-2xl shadow-sm p-8 w-full max-w-sm text-center">
          <div class="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-emerald-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
              <polyline points="20 6 9 17 4 12"/>
            </svg>
          </div>
          <h2 class="text-lg font-semibold text-emerald-700 mb-2">Upload Complete!</h2>
          <p class="text-sm text-gray-500">Your file has been received. You can close this page.</p>
        </div>
      }

      <!-- Error -->
      @if (state() === 'error') {
        <div class="bg-white rounded-2xl shadow-sm p-6 w-full max-w-sm text-center">
          <div class="text-4xl mb-3">❌</div>
          <h2 class="text-base font-semibold text-red-700 mb-2">Upload Failed</h2>
          <p class="text-sm text-gray-500 mb-4">{{ errorMsg() }}</p>
          <button (click)="state.set('idle')"
                  class="w-full py-3 bg-sage-600 text-white font-semibold rounded-xl">
            Try Again
          </button>
        </div>
      }

      <p class="text-xs text-gray-300 mt-8">Powered by Lodgik PMS</p>
    </div>
  `,
})
export class MobileUploadPage implements OnInit {
  private route = inject(ActivatedRoute);
  private http  = inject(HttpClient);

  state    = signal<PageState>('idle');
  label    = signal('');
  fileError = signal('');
  errorMsg  = signal('');
  progress  = signal(0);

  private token = '';
  // environment.apiUrl = 'https://api.lodgik.co/api' — strip the trailing /api
  // because the URL templates below already include /api/...
  private apiBase = ((environment as any).apiUrl as string).replace(/\/api$/, '');

  ngOnInit(): void {
    this.token = this.route.snapshot.paramMap.get('token') ?? '';
    if (!this.token) {
      this.state.set('expired');
      return;
    }
    // Optionally fetch token metadata to show the label and verify it's still pending
    this.http.get<any>(`${this.apiBase}/api/upload/qr-token/${this.token}/status`).subscribe({
      next: (r) => {
        if (r?.data?.status === 'done') {
          this.state.set('used');
        } else if (r?.data?.label) {
          this.label.set(r.data.label);
        }
      },
      error: (e) => {
        if (e?.status === 410 || e?.status === 404) this.state.set('expired');
      },
    });
  }

  onFileSelected(event: Event): void {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;

    this.fileError.set('');

    // Validate size (10 MB)
    if (file.size > 10 * 1024 * 1024) {
      this.fileError.set('File is too large. Maximum size is 10 MB.');
      return;
    }

    this.state.set('uploading');
    this.progress.set(0);

    const reader = new FileReader();
    reader.onprogress = (e) => {
      if (e.lengthComputable) this.progress.set(Math.round((e.loaded / e.total) * 50));
    };
    reader.onload = () => {
      this.progress.set(60);
      const base64 = reader.result as string;
      this.http.post<any>(`${this.apiBase}/api/upload/qr/${this.token}`, {
        file_base64: base64,
        filename:    file.name,
      }).subscribe({
        next: () => {
          this.progress.set(100);
          this.state.set('done');
        },
        error: (e) => {
          this.state.set('error');
          if (e?.status === 409) {
            this.state.set('used');
          } else if (e?.status === 410) {
            this.state.set('expired');
          } else {
            this.errorMsg.set(e?.error?.message || e?.error?.error || 'Upload failed. Please try again.');
          }
        },
      });
    };
    reader.onerror = () => {
      this.state.set('error');
      this.errorMsg.set('Could not read the file. Please try again.');
    };
    reader.readAsDataURL(file);
  }
}
